drop table MYBLOG_USERS if exists;
drop table MYBLOG_POSTS if exists;

create table MYBLOG_USERS (ID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY, USER_NAME varchar(50) not null, PASSWORD varchar(50) not null);
create table MYBLOG_POSTS (ID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY, USER_ID integer, TITLE varchar(100), CREATION_DATE date not null, CONTENT varchar(999));
       
alter table MYBLOG_POSTS add constraint FK_AUTHOR foreign key (USER_ID) references MYBLOG_USERS(ID) on delete cascade;